### ISSUE TITLE
Newer version of net-misc/networkmanager required by net-libs/libnm-qt not available

### ISSUE THREAD

**Issue by chusopr** [funtoo/funtoo-overlay#40]
Compilation of net-libs/libnm-qt fails with following error:

```
/var/tmp/portage/net-libs/libnm-qt-0.9.8.1/work/libnm-qt-0.9.8.1/manager.cpp:656:14: error: ‘NM_CONNECTIVITY_UNKNOWN’ was not declared in this scope
         case NM_CONNECTIVITY_UNKNOWN:
              ^
/var/tmp/portage/net-libs/libnm-qt-0.9.8.1/work/libnm-qt-0.9.8.1/manager.cpp:659:14: error: ‘NM_CONNECTIVITY_NONE’ was not declared in this scope
         case NM_CONNECTIVITY_NONE:
              ^
/var/tmp/portage/net-libs/libnm-qt-0.9.8.1/work/libnm-qt-0.9.8.1/manager.cpp:662:14: error: ‘NM_CONNECTIVITY_PORTAL’ was not declared in this scope
         case NM_CONNECTIVITY_PORTAL:
              ^
/var/tmp/portage/net-libs/libnm-qt-0.9.8.1/work/libnm-qt-0.9.8.1/manager.cpp:665:14: error: ‘NM_CONNECTIVITY_LIMITED’ was not declared in this scope
         case NM_CONNECTIVITY_LIMITED:
              ^
/var/tmp/portage/net-libs/libnm-qt-0.9.8.1/work/libnm-qt-0.9.8.1/manager.cpp:668:14: error: ‘NM_CONNECTIVITY_FULL’ was not declared in this scope
         case NM_CONNECTIVITY_FULL:
```

This undefined constants were introduced in NetworkManager 0.9.8.6 (http://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/include/NetworkManager.h, line 105). But Funtoo seems to be stalled at net-misc/networkmanager-0.9.8.2-r2 while Gentoo is at net-misc/networkmanager-0.9.8.8.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2010

**Comment by danielrobbins** [comment]
This issue has been resolved. See resolution here: https://bugs.funtoo.org/browse/FL-2010
